import * as THREE from './vendor/three.module.min.js';

// 全景角度单位为度：yaw 0 = 图像正中 / 平面朝上，正 yaw 朝右；正 pitch 朝上。
// 可在 data.js 中用 window.PANORAMA_CONFIG = {start, nodes:[...]} 覆盖本配置。
const DEFAULT_NODES=[
  {id:'courtyard',title:'户外庭院（待确认）',room:'outdoor',position_mm:[6400,-6500],image:'assets/pano-courtyard.png',reference:'assets/ref-courtyard.png',heading:0,mapHeading:0,pitch:0,links:['cafe'],hotspots:[{target:'cafe',yaw:0,pitch:-12,label:'进入咖啡厅'}]},
  {id:'cafe',title:'咖啡吧台',room:'cafe',position_mm:[3300,2400],image:'assets/pano-cafe.png',reference:'assets/ref-bar.png',heading:0,mapHeading:0,pitch:0,links:['courtyard','seating'],hotspots:[{target:'courtyard',yaw:180,pitch:-14,label:'回到庭院'},{target:'seating',yaw:80,pitch:-12,label:'走到桌椅区'}]},
  {id:'seating',title:'桌椅与主题展示窗',room:'cafe',position_mm:[8800,3000],image:'assets/pano-seating.png',reference:'assets/ref-cafe.png',heading:0,mapHeading:90,pitch:0,links:['cafe','salon'],hotspots:[{target:'cafe',yaw:-145,pitch:-12,label:'转回吧台'},{target:'salon',yaw:-85,pitch:-10,label:'进入沙龙'}]},
  {id:'salon',title:'收藏者客厅',room:'salon',position_mm:[9700,7300],image:'assets/pano-salon.png',reference:'assets/ref-salon.png',heading:0,mapHeading:0,pitch:0,links:['seating','gallery'],hotspots:[{target:'seating',yaw:180,pitch:-12,label:'返回咖啡厅'},{target:'gallery',yaw:85,pitch:-10,label:'进入展厅'}]},
  {id:'gallery',title:'私人收藏展厅',room:'gallery',position_mm:[18400,6400],image:'assets/pano-gallery.png',reference:'assets/ref-gallery.png',heading:0,mapHeading:0,pitch:0,links:['salon'],hotspots:[{target:'salon',yaw:-80,pitch:-10,label:'返回沙龙'}]}
];
const config=window.PANORAMA_CONFIG||{},nodes=Array.isArray(config.nodes)?config.nodes:DEFAULT_NODES,byId=new Map(nodes.map(n=>[n.id,n]));
const START=byId.has(config.start)?config.start:'cafe';
const $=id=>document.getElementById(id),D2R=Math.PI/180,R2D=180/Math.PI,DEFAULT_FOV=76,MIN_FOV=42,MAX_FOV=96;
const canvas=$('panoCanvas'),modals=[$('planDialog'),$('referenceDialog'),$('helpDialog')];
const state={node:null,yaw:0,pitch:0,fov:DEFAULT_FOV,loading:false,clean:false};
let renderer,scene,camera,sphere,material,currentTexture=null,pendingTexture=null,queued=null,failedTarget=null,disposed=false,frameId=0,toastTimer=0,firstNavigation=true,refToken=0;
const loader=new THREE.TextureLoader(),pointers=new Map(),hotspotObjects=[],mapMarkers=[],openers=new WeakMap();
let drag=null,pinch=null,gestureDistance=0;
const projected=new THREE.Vector3(),forward=new THREE.Vector3(),lookTarget=new THREE.Vector3();
const reduceMotion=matchMedia('(prefers-reduced-motion:reduce)').matches;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,reduceMotion?0:ms));
const nextPaint=()=>new Promise(resolve=>requestAnimationFrame(()=>resolve()));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function icon(name){const n=document.createElementNS('http://www.w3.org/2000/svg','svg'),use=document.createElementNS(n.namespaceURI,'use');use.setAttribute('href','#i-'+name);n.append(use);n.setAttribute('aria-hidden','true');return n;}
function text(tag,value,cls){const n=document.createElement(tag);n.textContent=value||'';if(cls)n.className=cls;return n;}
function toast(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function hasModal(){return modals.some(d=>d.open);}
function normalizeYaw(){state.yaw=THREE.MathUtils.euclideanModulo(state.yaw+Math.PI,Math.PI*2)-Math.PI;state.pitch=clamp(state.pitch,-89*D2R,89*D2R);}
function disposeTexture(texture){if(!texture)return;texture.dispose();const source=texture.image;if(source?.removeAttribute)source.removeAttribute('src');if(texture.source)texture.source.data=null;}
function invalidate(){if(disposed||frameId||document.hidden||!renderer)return;frameId=requestAnimationFrame(draw);}
function applyCamera(){normalizeYaw();lookTarget.set(Math.sin(state.yaw)*Math.cos(state.pitch),Math.sin(state.pitch),-Math.cos(state.yaw)*Math.cos(state.pitch));camera.lookAt(lookTarget);camera.fov=state.fov;camera.updateProjectionMatrix();camera.updateMatrixWorld(true);}
function draw(){frameId=0;if(disposed||document.hidden||!renderer)return;applyCamera();renderer.render(scene,camera);projectHotspots();updateMapHeading();}
function projectHotspots(){if(!camera)return;camera.getWorldDirection(forward);const w=canvas.clientWidth,h=canvas.clientHeight;for(const spot of hotspotObjects){const dot=spot.position.dot(forward);projected.copy(spot.position).project(camera);const x=(projected.x*.5+.5)*w,y=(-projected.y*.5+.5)*h,visible=currentTexture&&!state.loading&&dot>0&&projected.z<1&&x>23&&x<w-23&&y>25&&y<h-25;spot.button.hidden=!visible;if(!visible)continue;spot.button.classList.toggle('opens-left',x>w*.66);const ring=spot.button.querySelector('.hotspot-ring'),anchor=ring.offsetLeft+ring.offsetWidth/2;spot.button.style.left=x+'px';spot.button.style.top=y+'px';spot.button.style.transform=`translate(${-anchor}px,-50%)`;}}
function setZoom(fov){state.fov=clamp(fov,MIN_FOV,MAX_FOV);$('zoomValue').textContent=(Math.tan(DEFAULT_FOV*D2R/2)/Math.tan(state.fov*D2R/2)).toFixed(1)+'×';$('zoomIn').disabled=state.fov<=MIN_FOV;$('zoomOut').disabled=state.fov>=MAX_FOV;invalidate();}
function resetView(){const n=byId.get(state.node)||byId.get(START);state.yaw=(n.heading||0)*D2R;state.pitch=(n.pitch||0)*D2R;setZoom(n.fov||DEFAULT_FOV);}
function hashNode(){let hash=location.hash.slice(1);try{hash=decodeURIComponent(hash);}catch{}return byId.has(hash)?hash:START;}
function allowedMove(target){const n=byId.get(state.node);return n&&(n.links||[]).includes(target);}
function requestMove(target){if(!allowedMove(target))return;navigate(target,{push:true,focus:true});}

async function imageFailureMessage(path){
  return navigator.onLine === false
    ? '网络暂时断开，当前画面可以继续观看。连接网络后，请点“重新读取”。'
    : '这张全景暂时未加载完成。请点“重新读取”；也可以刷新当前网址重试。';
}
async function loadTexture(path){return new Promise((resolve,reject)=>{pendingTexture=loader.load(path,texture=>{if(disposed){disposeTexture(texture);reject(new Error('查看器已关闭。'));return;}const image=texture.image,w=image.naturalWidth||image.width,h=image.naturalHeight||image.height;if(!w||!h||w!==2*h){disposeTexture(texture);pendingTexture=null;reject(new Error(`当前文件为 ${w}×${h}，不是 2:1 等距柱状全景。请使用专门的全景图；普通效果图不能直接贴球。`));return;}texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(4,renderer.capabilities.getMaxAnisotropy());texture.wrapS=THREE.RepeatWrapping;texture.wrapT=THREE.ClampToEdgeWrapping;texture.needsUpdate=true;resolve(texture);},undefined,async()=>{if(pendingTexture){disposeTexture(pendingTexture);pendingTexture=null;}reject(new Error(await imageFailureMessage(path)));});});}
async function navigate(id,{push=true,focus=false}={}){
  if(!byId.has(id)||disposed)return;
  if(state.loading){queued={id,push,focus};return;}
  if(state.node===id&&currentTexture){modals.forEach(d=>d.open&&d.close());return;}
  state.loading=true;failedTarget=id;$('errorPanel').hidden=true;$('switchText').textContent='正在进入'+byId.get(id).title+'…';$('switchStatus').hidden=!currentTexture;modals.forEach(d=>d.open&&d.close());invalidate();
  try{
    const n=byId.get(id),texture=await loadTexture(n.image);if(disposed)return;
    $('transitionShade').classList.add('is-dark');await pause(currentTexture?170:0);
    const old=currentTexture;currentTexture=texture;pendingTexture=null;material.map=texture;material.needsUpdate=true;state.node=id;resetView();updateSceneUI();
    if(push&&hashNode()!==id)history.pushState({node:id},'', '#'+encodeURIComponent(id));else if(firstNavigation&&!location.hash)history.replaceState({node:id},'', '#'+encodeURIComponent(id));firstNavigation=false;
    $('initialLoading').hidden=true;applyCamera();renderer.render(scene,camera);disposeTexture(old);await nextPaint();$('transitionShade').classList.remove('is-dark');await pause(210);
    $('errorPanel').hidden=true;if(focus)$('sceneTitle').focus({preventScroll:true});$('announcement').textContent='当前全景：'+n.title+'。拖动可以环顾四周。';
  }catch(error){
    if(disposed)return;$('initialLoading').hidden=true;$('transitionShade').classList.remove('is-dark');$('errorText').textContent=error.message||'全景暂时无法读取。';$('dismissError').hidden=!currentTexture;$('errorPanel').hidden=false;$('retryLoad').focus({preventScroll:true});
  }finally{
    state.loading=false;$('switchStatus').hidden=true;invalidate();const next=queued;queued=null;if(next&&next.id!==state.node)navigate(next.id,next);
  }
}
function updateSceneUI(){const n=byId.get(state.node);$('sceneTitle').textContent=n.title;$('sceneNumber').textContent=String(nodes.indexOf(n)+1).padStart(2,'0')+' / '+String(nodes.length).padStart(2,'0');document.title=n.title+' · 長 chang 设计全景';const links=$('sceneLinks');links.replaceChildren();for(const id of n.links||[]){const dest=byId.get(id);if(!dest)continue;const button=text('button',null,'scene-link');button.append(text('span',dest.title),icon('arrow'));button.setAttribute('aria-label','切换到'+dest.title);button.addEventListener('click',()=>requestMove(id));links.append(button);}
  hotspotObjects.length=0;$('hotspots').replaceChildren();for(const h of n.hotspots||[]){if(!(n.links||[]).includes(h.target)||!byId.has(h.target))continue;const button=text('button',null,'hotspot'),ring=text('span',null,'hotspot-ring');ring.append(icon('go'));button.append(ring,text('span',h.label||byId.get(h.target).title));button.dataset.target=h.target;button.setAttribute('aria-label',h.label||'切换到'+byId.get(h.target).title);button.addEventListener('click',()=>requestMove(h.target));const yaw=h.yaw*D2R,pitch=h.pitch*D2R,position=new THREE.Vector3(Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch)).multiplyScalar(10);hotspotObjects.push({button,position});$('hotspots').append(button);}
  document.querySelectorAll('.plan-svg .map-room').forEach(g=>g.classList.toggle('is-current',g.dataset.room===n.room));$('planPositions').querySelectorAll('button').forEach(b=>b.setAttribute('aria-current',b.dataset.node===state.node?'location':'false'));updateMapHeading();
}

function openModal(dialog,opener){if(dialog.open)return;pointers.clear();drag=pinch=null;modals.filter(d=>d!==dialog&&d.open).forEach(d=>d.close());openers.set(dialog,opener||document.activeElement);dialog.showModal();dialog.querySelector('.close-dialog').focus({preventScroll:true});}
for(const dialog of modals){dialog.querySelector('.close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target!==dialog)return;const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});dialog.addEventListener('keydown',e=>{if(e.key!=='Tab'||!dialog.open)return;const items=[...dialog.querySelectorAll('button:not([disabled]),a[href],[tabindex]:not([tabindex="-1"])')].filter(n=>n.tabIndex>=0&&n.getClientRects().length&&!n.closest('[hidden],[inert],[aria-hidden="true"]')&&getComputedStyle(n).visibility!=='hidden');e.preventDefault();if(!items.length){dialog.tabIndex=-1;dialog.focus();return;}const i=items.indexOf(document.activeElement),next=i<0?(e.shiftKey?items.length-1:0):(i+(e.shiftKey?-1:1)+items.length)%items.length;items[next].focus({preventScroll:true});});dialog.addEventListener('close',()=>{if(dialog===$('referenceDialog')){++refToken;$('referenceImage').onload=null;$('referenceImage').onerror=null;$('referenceImage').removeAttribute('src');$('referenceImage').hidden=true;}if(!hasModal()){const opener=openers.get(dialog);if(opener?.isConnected)opener.focus({preventScroll:true});}});}
function showReference(id){const n=byId.get(id);if(!n)return;const image=$('referenceImage'),token=++refToken;image.onload=null;image.onerror=null;image.removeAttribute('src');image.hidden=true;$('referenceStatus').hidden=false;$('referenceStatus').textContent='正在读取原效果图…';$('referenceCaption').textContent=n.title+(n.id==='courtyard'?' · 附录候选方案':' · 本次采用效果图');$('referenceTabs').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.node===id)));image.alt=n.title+'原效果图';image.onload=()=>{if(token!==refToken)return;image.hidden=false;$('referenceStatus').hidden=true;};image.onerror=()=>{if(token!==refToken)return;$('referenceStatus').textContent='暂时无法读取原图，请确认 assets 中的参考文件完整。';};image.src=n.reference;}
for(const n of nodes){const b=text('button',n.title);b.dataset.node=n.id;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>showReference(n.id));$('referenceTabs').append(b);const quick=text('button',n.title);quick.dataset.node=n.id;quick.setAttribute('aria-label','快速定位到'+n.title);quick.addEventListener('click',()=>navigate(n.id,{focus:true}));$('planPositions').append(quick);}
$('openPlan').onclick=()=>openModal($('planDialog'),$('openPlan'));$('expandPlan').onclick=()=>openModal($('planDialog'),$('expandPlan'));$('openHelp').onclick=()=>openModal($('helpDialog'),$('openHelp'));$('openReference').onclick=()=>{openModal($('referenceDialog'),$('openReference'));showReference(state.node||START);};
$('miniToggle').onclick=()=>{const open=$('miniToggle').getAttribute('aria-expanded')==='true';$('miniToggle').setAttribute('aria-expanded',String(!open));$('miniBody').hidden=open;};
$('zoomIn').onclick=()=>setZoom(state.fov-6);$('zoomOut').onclick=()=>setZoom(state.fov+6);$('resetView').onclick=resetView;
$('retryLoad').onclick=()=>navigate(failedTarget||START,{push:true});$('dismissError').onclick=()=>{$('errorPanel').hidden=true;canvas.focus();};
function clean(value){state.clean=value;document.body.classList.toggle('is-clean',value);$('showUI').hidden=!value;(value?$('showUI'):$('hideUI')).focus({preventScroll:true});}
$('hideUI').onclick=()=>clean(true);$('showUI').onclick=()=>clean(false);
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('当前浏览器未提供此全屏方式。');}catch{toast('浏览器未进入全屏，可使用 F11。');}};
document.addEventListener('fullscreenchange',()=>{$('fullscreen').setAttribute('aria-label',document.fullscreenElement?'退出全屏':'全屏浏览');resize();});

canvas.addEventListener('pointerdown',e=>{if(hasModal()||!currentTexture||(e.pointerType==='mouse'&&e.button!==0))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});canvas.setPointerCapture(e.pointerId);canvas.focus();gestureDistance=0;if(pointers.size===1)drag={x:e.clientX,y:e.clientY,yaw:state.yaw,pitch:state.pitch};if(pointers.size===2){const[a,b]=[...pointers.values()];pinch={distance:Math.hypot(a.x-b.x,a.y-b.y),fov:state.fov};drag=null;}canvas.classList.add('is-dragging');});
canvas.addEventListener('pointermove',e=>{if(!pointers.has(e.pointerId)||hasModal())return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&pinch){const[a,b]=[...pointers.values()],distance=Math.max(1,Math.hypot(a.x-b.x,a.y-b.y));setZoom(pinch.fov*pinch.distance/distance);return;}if(drag){const dx=e.clientX-drag.x,dy=e.clientY-drag.y;gestureDistance=Math.hypot(dx,dy);state.yaw=drag.yaw-dx*.0033;state.pitch=drag.pitch+dy*.0033;invalidate();}});
function releasePointer(e){pointers.delete(e.pointerId);if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);pinch=null;canvas.classList.remove('is-dragging');if(pointers.size===1){const p=[...pointers.values()][0];drag={x:p.x,y:p.y,yaw:state.yaw,pitch:state.pitch};}else drag=null;}
canvas.addEventListener('pointerup',releasePointer);canvas.addEventListener('pointercancel',releasePointer);canvas.addEventListener('wheel',e=>{if(hasModal()||!currentTexture)return;e.preventDefault();setZoom(state.fov+e.deltaY*.032);},{passive:false});
document.addEventListener('keydown',e=>{if(hasModal()||e.ctrlKey||e.metaKey||e.altKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','+','=','-','_'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')state.yaw-=3*D2R;else if(e.key==='ArrowRight')state.yaw+=3*D2R;else if(e.key==='ArrowUp')state.pitch+=3*D2R;else if(e.key==='ArrowDown')state.pitch-=3*D2R;else if(e.key==='Home')resetView();else if(e.key==='+'||e.key==='=')setZoom(state.fov-4);else if(e.key==='-'||e.key==='_')setZoom(state.fov+4);else if(e.key.toLowerCase()==='h')clean(!state.clean);else if(e.key==='Escape'&&state.clean)clean(false);invalidate();});
window.addEventListener('popstate',()=>navigate(hashNode(),{push:false}));window.addEventListener('hashchange',()=>navigate(hashNode(),{push:false}));document.addEventListener('visibilitychange',()=>{pointers.clear();drag=pinch=null;if(document.hidden&&frameId){cancelAnimationFrame(frameId);frameId=0;}else invalidate();});

function svgNode(tag,attrs={}){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;}
function polygonCenter(ps){let area=0,x=0,y=0;for(let i=0;i<ps.length;i++){const a=ps[i],b=ps[(i+1)%ps.length],c=a[0]*b[1]-b[0]*a[1];area+=c;x+=(a[0]+b[0])*c;y+=(a[1]+b[1])*c;}return Math.abs(area)>1e-8?[x/(3*area),y/(3*area)]:ps[0];}
const geometry=window.SPACE_DATA||{},rooms=(Array.isArray(geometry.rooms)?geometry.rooms:[]).map(r=>({...r,polygon:r.polygon_mm||r.polygon,area:r.reference_area_m2??r.area})).filter(r=>r.polygon?.length>=3);
const outside=geometry.outdoor?.boundary_mm||geometry.outdoor?.polygon;if(outside?.length>=3&&!rooms.some(r=>r.id==='outdoor'))rooms.push({id:'outdoor',name:'户外外摆',area:200,polygon:outside});
function makeMap(mini){const svg=svgNode('svg',{class:'plan-svg',role:mini?'img':'group','aria-label':mini?'全景位置与朝向':'平面快速定位',preserveAspectRatio:'xMidYMid meet'}),points=rooms.flatMap(r=>r.polygon);if(!points.length){svg.setAttribute('viewBox','0 0 300 150');const t=svgNode('text',{x:150,y:75,'text-anchor':'middle',fill:'#b6a385','font-size':12});t.textContent='平面数据待载入';svg.append(t);return svg;}const minX=Math.min(...points.map(p=>p[0])),maxX=Math.max(...points.map(p=>p[0])),minY=Math.min(...points.map(p=>p[1])),maxY=Math.max(...points.map(p=>p[1])),w=maxX-minX,h=maxY-minY,pad=Math.max(w,h)*.045;svg.setAttribute('viewBox',`${-pad} ${-pad} ${w+pad*2} ${h+pad*2}`);const xy=p=>[p[0]-minX,maxY-p[1]],font=Math.max(w,h)*(mini?.044:.025),short={cafe:'咖啡',workshop:'操作',salon:'沙龙',gallery:'展厅',outdoor:'外摆'};
  for(const r of rooms){const group=svgNode('g',{class:'map-room','data-room':r.id}),dest=nodes.find(n=>n.room===r.id);group.append(svgNode('polygon',{points:r.polygon.map(p=>xy(p).join(',')).join(' '),class:'room-shape'+(r.id==='outdoor'?' outdoor-shape':'')}));if(!mini&&dest){group.setAttribute('role','button');group.setAttribute('tabindex','0');group.setAttribute('aria-label',`快速定位：${r.name}`);group.addEventListener('click',()=>navigate(dest.id,{focus:true}));group.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();navigate(dest.id,{focus:true});}});}else if(!dest)group.setAttribute('aria-label',r.name+'，暂无全景');svg.append(group);}
  for(const c of geometry.building?.columns||geometry.columns||[]){const r=c.rect_mm||c.rect;if(!r)continue;const p=xy([r[0],r[3]]);svg.append(svgNode('rect',{x:p[0],y:p[1],width:r[2]-r[0],height:r[3]-r[1],class:'map-column'}));}for(const d of geometry.doors||[]){const a=d.a_mm||d.a,b=d.b_mm||d.b;if(!a||!b)continue;const p=xy(a),q=xy(b);svg.append(svgNode('line',{x1:p[0],y1:p[1],x2:q[0],y2:q[1],class:'map-door'}));}
  for(const r of rooms){let pos=polygonCenter(r.polygon);if(mini){const xs=r.polygon.map(p=>p[0]),ys=r.polygon.map(p=>p[1]),l=Math.min(...xs),rr=Math.max(...xs),b=Math.min(...ys),t=Math.max(...ys);if(r.id==='gallery')pos=[(l+rr)/2,b+(t-b)*.78];if(r.id==='cafe')pos=[(l+rr)/2,b+(t-b)*.23];if(r.id==='salon')pos=[(l+rr)/2,b+(t-b)*.72];}const p=xy(pos),title=svgNode('text',{x:p[0],y:p[1]-(mini?0:font*.3),'font-size':font,class:'map-label'});title.textContent=mini?(short[r.id]||r.name):r.name;svg.append(title);if(!mini){const sub=svgNode('text',{x:p[0],y:p[1]+font*.85,'font-size':font*.6,class:'map-area'});sub.textContent=r.id==='workshop'?'暂无全景':Number.isFinite(Number(r.area))?Number(r.area).toFixed(2)+' ㎡':'';svg.append(sub);}}
  const marker=svgNode('g',{'aria-hidden':'true'}),arrow=svgNode('g');marker.append(svgNode('circle',{cx:0,cy:0,r:540,class:'position-halo'}));arrow.append(svgNode('path',{d:'M0 -1200 L500 480 L0 230 L-500 480 Z',class:'position-arrow'}));marker.append(arrow);svg.append(marker);mapMarkers.push({marker,arrow,minX,maxY});return svg;
}
function updateMapHeading(){const n=byId.get(state.node||START);if(!n?.position_mm)return;for(const m of mapMarkers){m.marker.setAttribute('transform',`translate(${n.position_mm[0]-m.minX} ${m.maxY-n.position_mm[1]})`);m.arrow.setAttribute('transform',`rotate(${state.yaw*R2D+(Number(n.mapHeading)||0)})`);}}
$('miniMap').replaceChildren(makeMap(true));$('largeMap').replaceChildren(makeMap(false));if(matchMedia('(max-width:680px)').matches){$('miniToggle').setAttribute('aria-expanded','false');$('miniBody').hidden=true;$('gestureHint').textContent='单指环顾 · 双指调整视野';}
function resize(){if(!renderer)return;const w=canvas.clientWidth||innerWidth,h=canvas.clientHeight||innerHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();invalidate();}
window.addEventListener('resize',resize);
Object.defineProperty(window,'__PANO_STATE',{get:()=>Object.freeze({node:state.node,yaw:state.yaw*R2D,pitch:state.pitch*R2D,fov:state.fov,loading:state.loading,residentTextures:Number(Boolean(currentTexture))+Number(Boolean(pendingTexture)),gpuTextures:renderer?.info.memory.textures||0,clean:state.clean})});
try{
  renderer=new THREE.WebGLRenderer({canvas,antialias:false,alpha:false,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;renderer.setClearColor(0x201e1a,1);
  scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(DEFAULT_FOV,1,.1,100);camera.position.set(0,0,0);const sphereGeometry=new THREE.SphereGeometry(50,96,64);sphereGeometry.scale(-1,1,1);sphereGeometry.rotateY(-Math.PI/2);material=new THREE.MeshBasicMaterial({color:0xffffff,toneMapped:false});sphere=new THREE.Mesh(sphereGeometry,material);scene.add(sphere);resize();navigate(hashNode(),{push:false});
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('errorText').textContent='浏览器的全景画面暂时中断，请刷新页面恢复。';$('dismissError').hidden=true;$('errorPanel').hidden=false;$('retryLoad').onclick=()=>location.reload();});
}catch(error){$('initialLoading').hidden=true;$('errorText').textContent='浏览器未能建立全景画面：'+error.message;$('errorPanel').hidden=false;$('retryLoad').onclick=()=>location.reload();}
window.addEventListener('pagehide',event=>{if(event.persisted)return;disposed=true;if(frameId)cancelAnimationFrame(frameId);disposeTexture(currentTexture);disposeTexture(pendingTexture);currentTexture=pendingTexture=null;sphere?.geometry.dispose();material?.dispose();renderer?.dispose();});


