import * as THREE from './vendor/three.module.min.js';
// Plan coordinates are metres: [east, north, height] -> Three [east, height, -north].
// All footprint sources are read at runtime from R20; vertical details are illustrative.
window.RENDER_READY=false;window.RENDER_ERRORS=[];
const $=s=>document.querySelector(s), P=(x,y,h=0)=>new THREE.Vector3(x,h,-y);
const params=new URLSearchParams(location.search);if(params.has('clean'))document.body.classList.add('clean');
// The image gallery is the default mobile experience; this renderer is opt-in.
const CAPTURE=params.has('capture')||params.has('clean');
const MOBILE=!CAPTURE&&(matchMedia('(pointer: coarse)').matches||innerWidth<760||navigator.connection?.saveData||navigator.deviceMemory&&navigator.deviceMemory<=4);
const PIXEL_RATIO=CAPTURE?Math.min(devicePixelRatio,1.5):MOBILE?1:Math.min(devicePixelRatio,1.25);
const scene=new THREE.Scene();scene.background=new THREE.Color('#ded8cf');
const camera=new THREE.PerspectiveCamera(65,innerWidth/innerHeight,.04,150);
const renderer=new THREE.WebGLRenderer({antialias:!MOBILE,preserveDrawingBuffer:CAPTURE,powerPreference:MOBILE?'low-power':'default'});
renderer.setPixelRatio(PIXEL_RATIO);renderer.setSize(innerWidth,innerHeight);
renderer.shadowMap.enabled=!MOBILE;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=true;
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;document.body.prepend(renderer.domElement);
window.RENDER_PROFILE={mobile:MOBILE,pixelRatio:PIXEL_RATIO,shadows:!MOBILE,capture:CAPTURE,frames:'on-demand'};
const material=(c,r=.78,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
const mats={wall:material('#cec4b4'),concrete:material('#a7a195'),wood:material('#bd9663'),woodDark:material('#78583c'),metal:material('#343b38',.45,.5),steel:material('#9ca2a0',.27,.75),floor:material('#cbc5b8'),paper:material('#f2e7d1'),model:material('#8e9691',.54,.2),black:material('#202924')};
const glassM=new THREE.MeshStandardMaterial({color:'#bad1ca',transparent:true,opacity:.13,roughness:.2,metalness:.08,side:THREE.DoubleSide,depthWrite:false});const fogM=glassM.clone();
const glow=new THREE.MeshBasicMaterial({color:'#ffe7b5'});
scene.add(new THREE.HemisphereLight('#fff3da','#727c73',2.3));
const sun=new THREE.DirectionalLight('#fff1d1',3);sun.position.set(11,24,15);sun.castShadow=!MOBILE;sun.shadow.mapSize.set(CAPTURE?2048:1024,CAPTURE?2048:1024);Object.assign(sun.shadow.camera,{left:-24,right:24,top:24,bottom:-24,near:1,far:70});sun.shadow.bias=-.0004;sun.target.position.set(12,0,-8);scene.add(sun,sun.target);
const light2=new THREE.DirectionalLight('#d7e4df',1.2);light2.position.set(28,11,-18);scene.add(light2);
const records=[], externals=new THREE.Group();scene.add(externals);
function mesh(geo,mat,name,parent=scene){const o=new THREE.Mesh(geo,mat);o.name=name;o.castShadow=!mat.transparent;o.receiveShadow=true;parent.add(o);return o;}
function box(x,y,z,w,d,h,mat,name='',parent=scene){const o=mesh(new THREE.BoxGeometry(w,h,d),mat,name,parent);o.position.copy(P(x,y,z));return o;}
function bounds(b,h,mat,name,z=h/2,parent=scene){return box((b[0]+b[2])/2,(b[1]+b[3])/2,z,b[2]-b[0],b[3]-b[1],h,mat,name,parent);}
function line(a,b,h=3.1,t=.12,mat=mats.wall,name='',base=0,parent=scene){let dx=b[0]-a[0],dy=b[1]-a[1];const o=box((a[0]+b[0])/2,(a[1]+b[1])/2,base+h/2,Math.hypot(dx,dy),t,h,mat,name,parent);o.rotation.y=Math.atan2(dy,dx);return o;}
// Identical labels share a texture/material; do not allocate one canvas for each model box.
const labelMaterials=new Map();
function label(text,x,y,z,w=.9,h=.22,normal='south',bg='#f3e9d7',fg='#26352f'){
 const key=JSON.stringify([text,w,h,bg,fg]);let mat=labelMaterials.get(key);
 if(!mat){const c=document.createElement('canvas');c.width=MOBILE?256:512;c.height=Math.max(48,Math.round(c.width*h/w));const t=c.getContext('2d');t.fillStyle=bg;t.fillRect(0,0,c.width,c.height);t.fillStyle=fg;t.textAlign='center';t.textBaseline='middle';t.font=`600 ${Math.min(c.width*82/768,c.height*.43)}px Microsoft YaHei, sans-serif`;text.split('\n').forEach((s,i,all)=>t.fillText(s,c.width/2,c.height*(i+.5)/all.length,c.width*.94));const tx=new THREE.CanvasTexture(c);tx.colorSpace=THREE.SRGBColorSpace;mat=new THREE.MeshBasicMaterial({map:tx,side:THREE.FrontSide});labelMaterials.set(key,mat);}
 return panelMesh(x,y,z,w,h,normal,mat,text);
}
function panelMesh(x,y,z,w,h,normal,mat,name){const o=mesh(new THREE.PlaneGeometry(w,h),mat,name);o.position.copy(P(x,y,z));o.rotation.y={south:0,north:Math.PI,east:Math.PI/2,west:-Math.PI/2}[normal]??0;o.castShadow=false;return o;}
function glass(a,b,h=2.8,name='',low=0,mat=glassM){line(a,b,h,.022,mat,name,low);line(a,b,.035,.055,mats.metal,name+' top',low+h);line(a,b,.04,.055,mats.metal,name+' sill',low);const L=Math.hypot(b[0]-a[0],b[1]-a[1]),n=Math.max(1,Math.ceil(L/1.2));for(let i=0;i<=n;i++){const f=i/n;box(a[0]+(b[0]-a[0])*f,a[1]+(b[1]-a[1])*f,low+h/2,.035,.035,h,mats.metal,name+' mullion');}}
function tabletop(b,code,steel=false,h=.75){const mat=steel?mats.steel:mats.wood;bounds(b,.07,mat,code+' top',h-.035);const m=.08;for(const x of [b[0]+m,b[2]-m])for(const y of [b[1]+m,b[3]-m])box(x,y,(h-.07)/2,.05,.05,h-.07,mats.metal,code+' leg');}
function stool(b,code,face='south'){const cx=(b[0]+b[2])/2,cy=(b[1]+b[3])/2,w=b[2]-b[0],d=b[3]-b[1];tabletop(b,code,false,.46);let sign=face==='south'?1:-1;if(face==='east'||face==='west')box(cx+(face==='east'?-1:1)*(w/2-.03),cy,.75,.055,d,.53,mats.wood,code+' back');else box(cx,cy+sign*(d/2-.03),.75,w,.055,.53,mats.wood,code+' back');}
function cylinder(x,y,z,r,h,mat,name){const o=mesh(new THREE.CylinderGeometry(r,r,h,16),mat,name);o.position.copy(P(x,y,z));return o;}
function books(x,y,z,n=4){for(let k=0;k<n;k++)box(x+k*.1,y,z,.08,.18,.22,[mats.paper,mats.woodDark,mats.metal][k%3],'book');}
function proxy(x,y,z,h,code){const s=h/1.75;const body=code.startsWith('G')?material(code==='G2'?'#899397':'#974d39',.35,.65):mats.model;const accent=code.startsWith('G')?material('#bcaa72',.35,.6):mats.model;box(x,y,z+.8*s,.4*s,.24*s,.65*s,body,code+' torso');box(x,y,z+1.32*s,.25*s,.24*s,.28*s,accent,code+' head');for(const q of [-1,1]){box(x+q*.14*s,y,z+.3*s,.17*s,.19*s,.55*s,body,code+' leg');box(x+q*.31*s,y,z+.8*s,.13*s,.17*s,.7*s,accent,code+' arm');}label(code+' · 占位模型',x,y-.25*s,z+.03,.65,.15,'south');}
function deck(b,code,h=.22){bounds(b,h,mats.woodDark,code,h/2);line([b[0],b[1]-.006],[b[2],b[1]-.006],.015,.015,glow,code+' glow',.04);}
function casework(f){const b=f.bounds_m,code=f.code,cx=(b[0]+b[2])/2,cy=(b[1]+b[3])/2;deck(b,code,.65);glass([b[0],b[1]],[b[2],b[1]],1.25,code,.65);glass([b[0],b[3]],[b[2],b[3]],1.25,code,.65);glass([b[0],b[1]],[b[0],b[3]],1.25,code,.65);glass([b[2],b[1]],[b[2],b[3]],1.25,code,.65);bounds(b,.035,mats.metal,code+' cap',1.91);if(code==='Q1'){for(let i=0;i<5;i++){let x=b[0]+(i+.5)*(b[2]-b[0])/5;proxy(x,cy,.68,.5,'Q'+(i+1));proxy(x,cy,1.25,.5,'Q'+(i+6));}bounds(b,.025,mats.wood,code+' shelf',1.22);}else if(code==='M1'){for(let k=0;k<4;k++)proxy(cx,cy,.68+k*.28,.24,'M'+(k+1));}else proxy(cx,cy,.67,.95,code);}
function wallWithOpenings(a,b,doors,h=3.1,parent=externals){const dx=b[0]-a[0],dy=b[1]-a[1],L=Math.hypot(dx,dy),ux=dx/L,uy=dy/L;let gaps=[];for(const [id,d] of Object.entries(doors)){const dist=p=>Math.abs((p[0]-a[0])*uy-(p[1]-a[1])*ux);if(dist(d.a)<.001&&dist(d.b)<.001){const q=p=>(p[0]-a[0])*ux+(p[1]-a[1])*uy;let l=Math.max(0,Math.min(q(d.a),q(d.b))),r=Math.min(L,Math.max(q(d.a),q(d.b)));if(r>l)gaps.push([l,r,id]);}}gaps.sort((x,y)=>x[0]-y[0]);const point=v=>[a[0]+ux*v,a[1]+uy*v];let p=0;for(const [l,r,id]of gaps){if(l>p)line(point(p),point(l),h,.12,mats.wall,'wall',0,parent);line(point(l),point(r),h-2.25,.12,mats.wall,'lintel '+id,2.25,parent);p=r;}if(p<L)line(point(p),b,h,.12,mats.wall,'wall',0,parent);}
const views=[
 {id:'overview',name:'总览 · 统一平面',position:[29,-11,22],target:[12,9,.5],fov:42},
 {id:'entrance',name:'01 入口与主吧',position:[4.15,.35,1.65],target:[2.1,3.7,1.35],fov:74},
 {id:'special',name:'02 特调与三联柜',position:[4.5,3.7,1.68],target:[2.15,7.55,1.3],fov:69},
 {id:'assembly',name:'03 半开放拼装',position:[11.23,3.85,1.68],target:[11.23,9.6,1.2],fov:72},
 {id:'workshop',name:'04 隔玻璃看修复',position:[8.1,10.1,1.68],target:[3.8,10.1,1.2],fov:73},
 {id:'viewing',name:'05 停看与公共通行',position:[7.35,7.25,1.68],target:[7.55,11.55,1.2],fov:78},
 {id:'story',name:'06 回廊 · 作品与收藏故事',position:[11.72,12.1,1.68],target:[11.72,10,1.4],fov:83},
 {id:'reading_north',name:'07 阅读 · 收藏与修复档案',position:[19.0,12.1,1.68],target:[19.3,18.05,1.3],fov:73},
 {id:'reading_south',name:'08 阅读 · 隔玻璃观展',position:[17.0,17.0,1.68],target:[20.7,10.3,1.1],fov:72},
 {id:'gallery_north',name:'09 珍藏 · 三格纳库位',position:[21.65,2.2,1.68],target:[19.2,8.0,1.25],fov:76},
 {id:'gallery_reverse',name:'10 珍藏 · 内门联系咖啡',position:[21.5,7.1,1.68],target:[15.8,4.9,1.15],fov:77},
 {id:'gallery_exit',name:'11 珍藏 · D03独立外门',position:[20.8,5.8,1.68],target:[21.9,0,1.15],fov:70}
];window.CAMERAS=views;
let renderFrame=0,renderTimer=0,lastRender=0,dirty=false,sceneReady=false,contextLost=false;
const FRAME_INTERVAL=MOBILE?1000/30:0;
function drawFrame(now){renderFrame=0;if(document.hidden||contextLost||!sceneReady)return;const wait=FRAME_INTERVAL-(now-lastRender);if(wait>1){renderTimer=setTimeout(()=>{renderTimer=0;render();},wait);return;}if(!dirty)return;dirty=false;renderer.render(scene,camera);lastRender=now;window.RENDER_READY=true;}
function render(){dirty=true;if(document.hidden||contextLost||!sceneReady||renderFrame||renderTimer)return;renderFrame=requestAnimationFrame(drawFrame);}
function pauseRendering(){if(renderFrame)cancelAnimationFrame(renderFrame);if(renderTimer)clearTimeout(renderTimer);renderFrame=0;renderTimer=0;drag=null;}
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseRendering();else render();});
window.addEventListener('pagehide',pauseRendering);window.addEventListener('pageshow',()=>render());
renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;pauseRendering();window.RENDER_READY=false;const error=$('#error');error.style.display='block';error.replaceChildren(document.createTextNode('三维显示已暂停。可返回轻量图集查看图片。 '));const a=document.createElement('a');a.href='../';a.textContent='返回图集';a.style.color='#fff';error.append(a);});
renderer.domElement.addEventListener('webglcontextrestored',()=>{contextLost=false;renderer.shadowMap.needsUpdate=true;$('#error').style.display='none';render();});
window.setView=function(id){const v=views.find(x=>x.id===id)||views[0];camera.position.copy(P(...v.position));camera.fov=v.fov;camera.lookAt(P(...v.target));camera.updateProjectionMatrix();$('#viewname').textContent=v.name;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v.id));window.CURRENT_VIEW=v.id;render();return v;};
window.setClean=v=>{document.body.classList.toggle('clean',v);render();};window.setFog=v=>{fogM.opacity=v?.7:.13;render();};window.getModelAudit=()=>window.SCENE_AUDIT;
window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);render();});
// Looking only: location is locked to audited named viewpoints. Drag never translates through a wall.
let drag=null;renderer.domElement.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,q:camera.quaternion.clone()};renderer.domElement.setPointerCapture(e.pointerId);});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;const eul=new THREE.Euler().setFromQuaternion(drag.q,'YXZ');eul.y-=(e.clientX-drag.x)*.003;eul.x=Math.max(-1.35,Math.min(1.35,eul.x-(e.clientY-drag.y)*.003));camera.quaternion.setFromEuler(eul);render();});renderer.domElement.addEventListener('pointerup',()=>drag=null);renderer.domElement.addEventListener('pointercancel',()=>drag=null);renderer.domElement.addEventListener('lostpointercapture',()=>drag=null);
async function main(){const [gr,mr]=await Promise.all([fetch('../R20_geometry.json'),fetch('./panels/manifest.json')]);if(!gr.ok)throw new Error('R20_geometry.json 尚未就绪；请从HTTP目录打开且保留同层文件。');const data=await gr.json(),manifest=await mr.json();window.MODEL_SOURCE=data;const shape=new THREE.Shape();data.site.slice(0,-1).forEach((v,i)=>i?shape.lineTo(...v):shape.moveTo(...v));const floor=mesh(new THREE.ShapeGeometry(shape),mats.floor,'floor');floor.rotation.x=-Math.PI/2;floor.position.y=-.012;floor.receiveShadow=true;
 for(let i=0;i<data.site.length-1;i++)wallWithOpenings(data.site[i],data.site[i+1],data.doors);
 for(const col of data.columns){const [x,y,z]=col.center_m,[w,d,h]=col.size_m;box(x,y,h/2,w,d,h,mats.concrete,col.name);records.push({id:col.name,type:'column',bounds:[x-w/2,y-d/2,x+w/2,y+d/2]});label(col.name.replace('SOURCE COLUMN C','Z'),x,y-d/2-.01,2.6,.32,.16);}
 const sh=data.shaft;box(sh.center_m[0],sh.center_m[1],sh.size_m[2]/2,...sh.size_m,mats.wall,'SHAFT');
 // Only two workshop partition planes are new; exterior boundaries are already cut above.
 wallWithOpenings([0,7.9],[6.504113,7.9],data.doors,3.1,scene);line([6.504113,7.9],[6.504113,9],3.1);line([6.504113,11.5],[6.504113,12.5],3.1);for(const seg of data.workshop_public_glass_m)glass(seg[0],seg[1],2.65,'REPAIR_OBSERVATION',0,fogM);line([6.504113,9],[6.504113,11.5],.45,.12,mats.wall,'observation head',2.65);
 for(const [id,d]of Object.entries(data.doors)){if(id==='D08')continue;const vertical=Math.abs(d.a[0]-d.b[0])<.01,L=Math.hypot(d.b[0]-d.a[0],d.b[1]-d.a[1]);let cx=(d.a[0]+d.b[0])/2,cy=(d.a[1]+d.b[1])/2;line(d.a,d.b,.06,.16,mats.metal,id+' head',2.2);for(const p of[d.a,d.b])box(p[0],p[1],1.1,.055,.055,2.2,mats.metal,id+' frame');label(id,cx+(vertical?.07:0),cy+(vertical?0:-.07),2.36,.42,.18,vertical?'east':'south');if(['D01','D06','D07'].includes(id)){line(d.a,d.b,2.17,.035,mats.woodDark,id+' leaf');box(cx+(vertical?.03:0),cy+(vertical?0:-.04),1,.035,.06,.11,mats.metal,id+' handle');}}
 for(const seg of data.no_door_glass||[])glass(seg[0],seg[1],2.8,'GALLERY_GLASS',0,fogM);const gd=data.doors.D08;glass(gd.a,gd.b,.035,'D08 lintel',2.78);glass(gd.hinge_m,gd.open_tip_m,2.25,'D08 OPEN INWARD');label('D08 · 咖啡内门',15.01,7.27,2.45,1.0,.18,'east');
 for(const p of data.assembly_partitions){if(p.kind==='story_back_wall')bounds(p.bounds_m,p.height_intent_m,mats.wall,p.code);else{bounds(p.bounds_m,.90,mats.wood,p.code);const b=p.bounds_m;glass([(b[0]+b[2])/2,b[1]],[(b[0]+b[2])/2,b[3]],.45,p.code,.90);}}
 for(const f of data.fixtures){const b=f.bounds_m;if(!b)continue;records.push({id:f.code,type:f.kind,bounds:b});if(f.kind==='story_panel')continue;if(f.kind==='wall_case'){bounds(b,1.1,mats.wood,f.code,1.55);continue;}if(f.kind==='desk'){tabletop(b,f.code,false,f.code.startsWith('A1')?.76:.75);if(f.code.startsWith('A1')){const x=(b[0]+b[2])/2;for(let k=0;k<5;k++){const y=b[1]+(k+.5)*(b[3]-b[1])/5;box(x,y,.805,.5,.36,.016,mats.metal,'cutting mat');box(x,y+.22,.86,.24,.035,.15,mats.woodDark,'tool rack');line([x-.26,y+.34],[x+.26,y+.34],.018,.02,glow,'task light',1.24);}}else books(b[0]+.2,b[1]+.25,.87,3);continue;}if(f.kind==='bench'){bounds(b,.09,mats.wood,f.code,.46);const north=f.code==='FNB2';box((b[0]+b[2])/2,north?b[3]-.025:b[1]+.025,.79,b[2]-b[0],.06,.6,mats.wood,f.code+' back');for(const x of[b[0]+.12,b[2]-.12])box(x,(b[1]+b[3])/2,.22,.07,.35,.44,mats.metal,f.code+' leg');continue;}if(f.code.startsWith('AS')){bounds(b,.9,mats.wood,f.code);label(f.code==='AS1'?'作品展示':'工具借还',(b[0]+b[2])/2,b[1]-.015,.64,.65,.16);continue;}if(f.kind==='retail_base_cabinet'){bounds(b,.9,mats.wood,f.code);continue;}if(f.kind==='retail_upper_shelves'){for(const z of f.shelf_top_heights_m){bounds(b,.04,mats.wood,f.code,z);for(let k=0;k<8;k++){const x=b[0]+.17+k*.34;box(x,(b[1]+b[3])/2,z+.16,.3,.15,.27,[mats.metal,mats.woodDark,mats.paper][k%3],'sealed kit');label(['HG','RG','MG'][k%3],x,b[1]-.006,z+.16,.27,.16);}}label('万代高达模型 · 全新盒装',11.23,9.825,2.11,2.6,.16);continue;}if(f.kind==='case'){casework(f);continue;}if(f.kind==='plinth'){deck(b,f.code,f.code==='U1'?.85:.2);if(f.code.startsWith('G')){const x=(b[0]+b[2])/2,y=(b[1]+b[3])/2;for(const xx of [b[0]+.055,b[2]-.055])box(xx,b[3]-.055,1.45,.045,.045,2.5,mats.metal,f.code+' open frame');box(x,b[3]-.055,2.68,b[2]-b[0],.045,.045,mats.metal,f.code+' frame top');proxy(x,y,.23,1.85,f.code);label(f.code+' · 格纳库主题位',x,b[1]-.008,.13,1.6,.19);for(const xx of[b[0]+.1,b[2]-.1])box(xx,b[3]-.15,1.45,.03,.035,2.4,glow,'hangar light');}else if(f.code==='U1'){proxy((b[0]+b[2])/2,(b[1]+b[3])/2,.9,.42,'样件');}else proxy((b[0]+b[2])/2,(b[1]+b[3])/2,.24,1.2,f.code);}}
 for(const e of data.retained_equipment){const b=e.bounds_m||[e.center_m[0]-e.size_m[0]/2,e.center_m[1]-e.size_m[1]/2,e.center_m[0]+e.size_m[0]/2,e.center_m[1]+e.size_m[1]/2];records.push({id:e.code,type:'equipment',bounds:b});if(e.code==='BK'){for(let k=0;k<3;k++){let x=b[0]+k*.75+.375;box(x,7.6,.44,.73,.58,.88,mats.wood,'BK drawer '+k);for(const z of[.2,.47,.74])box(x,7.288,z,.15,.018,.016,mats.metal,'BK handle');box(x,7.875,1.75,.72,.035,1.68,mats.wood,'BK perforated back');for(const xx of[x-.3625,x+.3625])box(xx,7.6,1.3,.025,.6,2.6,mats.steel,'BK frame');for(const z of[.9,1.4,1.92,2.58])box(x,7.58,z,.72,.55,.025,mats.wood,'BK shelf');for(let row=0;row<6;row++)for(let col=0;col<4;col++)box(x-.25+col*.165,7.85,1.07+row*.24,.012,.012,.012,mats.metal,'peg hole');books(x-.22,7.55,1.56,4);}continue;}if(e.code==='R1'||e.code==='R2'){tabletop(b,e.code,true,.9);box((b[0]+b[2])/2,(b[1]+b[3])/2,1.02,.6,.35,.17,mats.model,'repair specimen');if(e.code==='R1')box((b[0]+b[2])/2,b[3]-.02,1.6,b[2]-b[0],.05,.9,mats.wood,'tool board');continue;}if(e.code==='CB1'&&e.polygon_m){const s=new THREE.Shape();e.polygon_m.forEach((p,i)=>i?s.lineTo(...p):s.moveTo(...p));const g=new THREE.ExtrudeGeometry(s,{depth:.9,bevelEnabled:false});const m=mesh(g,mats.wood,'CB1 notch preserved');m.rotation.x=-Math.PI/2;box(.31,1.7,1.08,.52,.8,.35,mats.steel,'coffee machine');for(const y of[1.1,2.4])cylinder(.33,y,1.25,.13,.5,mats.metal,'grinder');continue;}if(e.code==='B3'){bounds(b,.87,mats.steel,e.code,.435);bounds(b,.05,mats.steel,'B3 rim',.915);for(const q of[[1.95,5.6,.58,.75],[2.6,5.6,.5,.75]]){box(q[0],q[1],.944,q[2],q[3],.012,mats.black,'recessed basin');box(q[0],q[1],.947,q[2]-.05,q[3]-.05,.008,mats.steel,'basin bottom');}cylinder(3.1,5.8,1.1,.023,.32,mats.steel,'tap');box(3.03,5.8,1.27,.18,.025,.025,mats.steel,'tap head');continue;}bounds(b,.95,mats.wood,e.code);bounds(b,.06,mats.metal,e.code+' top',.98);if(e.code==='B1'){box(2.22,1.1,1.2,.4,.45,.34,glassM,'pastry case');label('点单 · 取餐',2.535,1.75,.65,1.2,.22,'east');}}
 for(const c of data.chairs){let face=c.face||(c.code.startsWith('US')?'north':'south');stool(c.bounds_m,c.code,face);}

 const logoPromise=new Promise((resolve,reject)=>new THREE.TextureLoader().load('./official-logo.png',tx=>{tx.colorSpace=THREE.SRGBColorSpace;const lm=new THREE.MeshBasicMaterial({map:tx,transparent:true,depthWrite:false,side:THREE.FrontSide});lm.onBeforeCompile=shader=>{shader.fragmentShader=shader.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\n diffuseColor.a *= 1.0-dot(texture2D(map,vMapUv).rgb,vec3(0.333333)); diffuseColor.rgb=vec3(0.12,0.085,0.045);');};panelMesh(.075,1.72,2.25,2.7,2.7*571/1400,'east',lm,'Official original logo');resolve();},undefined,reject));

 const loads=[logoPromise];for(const a of manifest.assets){if(!a.reference_bounds_m)continue;const b=a.reference_bounds_m,[w,h]=a.graphic_face_size_m,n=a.front_normal;let x=(b[0]+b[2])/2,y=(b[1]+b[3])/2;if(n==='north')y=b[3]+.012;if(n==='south')y=b[1]-.012;if(n==='east')x=b[2]+.012;if(n==='west')x=b[0]-.012;const file=a.texture_png.split(/[\\/]/).pop();loads.push(new Promise((resolve,reject)=>new THREE.TextureLoader().load('./panels/'+encodeURIComponent(file),tx=>{tx.colorSpace=THREE.SRGBColorSpace;tx.anisotropy=MOBILE?1:Math.min(4,renderer.capabilities.getMaxAnisotropy());panelMesh(x,y,a.mount_bottom_intent_m+h/2,w,h,n,new THREE.MeshBasicMaterial({map:tx,side:THREE.FrontSide}),a.id);resolve();},undefined,reject)));}

 for(const a of manifest.assets.filter(a=>!a.reference_bounds_m)){
   const group=a.id.split('_')[0], fixture=data.fixtures.find(f=>f.code===group||f.code===group+'1');if(!fixture)continue;
   const b=fixture.bounds_m,[w,h]=a.graphic_face_size_m;const file=a.texture_png.split(/[\\/]/).pop();
   let normal='south',x=(b[0]+b[2])/2,y=b[1]-.015,z=.5;
   if(group==='G'){x=19.35;y=7.41;z=.55;}if(group==='H'){normal='west';x=b[0]-.015;y=(b[1]+b[3])/2;z=.42;}
   if(group==='V1'||group==='V2'){normal='east';x=b[2]+.015;y=(b[1]+b[3])/2;z=.43;}if(group==='U1'){normal='east';x=b[2]+.015;z=.7;}
   loads.push(new Promise((resolve,reject)=>new THREE.TextureLoader().load('./panels/'+encodeURIComponent(file),tx=>{tx.colorSpace=THREE.SRGBColorSpace;panelMesh(x,y,z,w,h,normal,new THREE.MeshBasicMaterial({map:tx,side:THREE.FrontSide}),a.id);resolve();},undefined,reject)));
 }
 await Promise.all(loads);
 // Low-density lighting tracks provide scale without an invented solid ceiling or beam grid.
 for(const y of[2.7,6.8,11.3,16.8]){let start=y>12.5?16:1,end=23;line([start,y],[end,y],.04,.045,mats.metal,'illustrative light track',3.04);for(let x=start+.8;x<end;x+=3){cylinder(x,y,2.94,.055,.17,mats.metal,'spot');cylinder(x,y,2.849,.045,.007,glow,'spot glow');}}
 const bay=box(6.97,10.25,.005,.89,2.5,.009,new THREE.MeshBasicMaterial({color:'#bfaa7d',transparent:true,opacity:.22}),'viewing bay');bay.castShadow=false;
 for(const v of views){let b=document.createElement('button');b.dataset.view=v.id;b.textContent=v.name;b.onclick=()=>window.setView(v.id);$('#views').append(b);}const fog=document.createElement('button');fog.textContent='雾化玻璃';let frosted=false;fog.onclick=()=>window.setFog(frosted=!frosted);$('#views').append(fog);
 window.SCENE_AUDIT={source:data.revision,columns:data.columns.length,chairs:data.chairs.length,cafeSeats:30,assemblySeats:10,storyTextures:manifest.assets.length,doors:Object.keys(data.doors),furniture:records,heights:'Vertical dimensions are illustrative except user-supplied BK height 2.6m; no site measured height claim',modelFigures:'Neutral numbered volume proxies, not actual inventory'};$('#status').textContent=`${data.columns.length}根图纸柱 · 30咖啡席 / 10拼装席 · ${manifest.assets.length}面故事图文 · 展品为编号体量示意`;sceneReady=true;renderer.shadowMap.needsUpdate=true;window.setView(params.get('view')||'overview');render();}
main().catch(e=>{window.RENDER_ERRORS.push(String(e));$('#error').style.display='block';$('#error').textContent='模型读取失败：'+e.message;console.error(e);});

window.auditMeshNumbers=()=>{const invalid=[];scene.traverse(o=>{if(o.isMesh){const a=o.geometry.attributes.position;for(let i=0;i<a.array.length;i++)if(!Number.isFinite(a.array[i])){invalid.push(o.name);break;}if(![o.position.x,o.position.y,o.position.z].every(Number.isFinite))invalid.push(o.name+' position');}});return invalid;};
